name: matLaw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - catalogue=2.0.10
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - cymem=2.0.6
  - cython-blis=0.7.9
  - datasets=3.3.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.17.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.28.1
  - huggingface_hub=0.29.2
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.20.1
  - langcodes=3.3.0
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lime=0.2.0.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - murmurhash=1.0.12
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.0
  - orc=2.1.1
  - overrides=7.4.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - preshed=3.0.9
  - prometheus_client=0.21.1
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=19.0.0
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - safetensors=0.5.3
  - scikit-image=0.25.0
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=78.1.1
  - shap=0.46.0
  - shellingham=1.5.0
  - six=1.17.0
  - skorch=1.1.0
  - slicer=0.0.8
  - smart_open=5.2.1
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.5.1
  - stack_data=0.2.0
  - tabulate=0.9.0
  - terminado=0.17.1
  - thinc=8.2.2
  - tifffile=2025.2.18
  - tinycss2=1.4.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.49.0
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wasabi=0.9.1
  - weasel=0.3.4
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - appnope==0.1.2; sys_platform == "darwin"
      - accelerate==1.2.1
      - annotated-types==0.7.0
      - arrow==1.3.0
      - attrs==25.3.0
      - autocorrect==2.6.1
      - captum==0.7.0
      - click==8.1.7
      - contourpy==1.3.0
      - cryptography==45.0.5
      - cycler==0.12.1
      - deprecation==2.1.0
      - dkpro-cassis==0.10.1
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.0
      - feedparser==6.0.12
      - fonttools==4.55.3
      - fqdn==1.5.1
      - fsspec==2025.3.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.30.2
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - isoduration==20.11.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - keopscore==2.1.1
      - kiwisolver==1.4.7
      - krippendorff==0.8.1
      - llvmlite==0.43.0
      - lxml==5.3.2
      - matplotlib==3.9.4
      - more-itertools==10.6.0
      - nltk==3.9.1
      - numba==0.60.0
      - packaging==25.0
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pfzy==0.3.4
      - prompt-toolkit==3.0.51
      - protobuf==5.29.1
      - psutil==7.0.0
      - pybind11==2.13.6
      - pykeops==2.1.1
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - pypdfium2==4.30.1
      - python-docx==1.1.2
      - scikit-learn==1.6.0
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - sgmllib3k==1.0.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - sty==1.0.6
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - toposort==1.10
      - torchinfo==1.8.0
      - types-python-dateutil==2.9.0.20241206
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - wandb==0.19.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
